version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports: 
      - '5432:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  etl-fhir:
    image: abuhamza1/etl-fhir:1.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - 'Z:\Documents\projects\exa-data-eng-assessment\test_data:/etl-fhir/data'
volumes:
  db_data: