version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgres
    ports: 
      - '5432:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: abuhamza1/etl-fhir
    depends_on:
      db:
        condition: service_healthy
    command: --host=db --port=5432 --user=postgres --password=postgrespassword
    volumes:
      - 'logs:/etl-fhird/logs'
      - 'path/to/data/directory:/etl-fhir/data'
volumes:
  db_data:
  logs: