create_tables_query = [
"""CREATE TABLE patient (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  extension JSONB,
  identifier JSONB,
  name JSONB,
  telecom JSONB,
  gender VARCHAR(10),
  birth_date VARCHAR(10),
  address JSONB,
  marital_status_coding JSONB,
  marital_status_text VARCHAR(25),
  communication JSONB
  );""",
"""CREATE TABLE encounter (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  identifier JSONB,
  status VARCHAR(25),
  class_code VARCHAR(10),
  type JSONB,
  subject_reference VARCHAR(45),
  subject TEXT,
  participant JSONB,
  period_start TIMESTAMP WITH TIME ZONE,
  period_end TIMESTAMP WITH TIME ZONE,
  reason_code JSONB,
  hospitalization_discharge_disposition_coding JSONB,
  hospitalization_discharge_disposition_text TEXT,
  location JSONB,
  service_provider_reference TEXT,
  service_provider_display TEXT
);""",
"""CREATE TABLE condition (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  clinical_status_coding JSONB,
  verification_status JSONB,
  category JSONB,
  code_coding JSONB,
  code_text TEXT,
  subject_reference VARCHAR(45),
  encounter_reference VARCHAR(45),
  onset_date_time TIMESTAMP WITH TIME ZONE,
  recorded_date TIMESTAMP WITH TIME ZONE
);""",
"""CREATE TABLE allergy_intolerance (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  clinical_status_coding JSONB,
  verification_status JSONB,
  type VARCHAR(25),
  category JSONB,
  criticality VARCHAR(25),
  patient_reference VARCHAR(45),
  code_coding JSONB,
  recorded_date TIMESTAMP WITH TIME ZONE,
  reaction JSONB
);""",
"""CREATE TABLE care_plan (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  status VARCHAR(25),
  intent VARCHAR(25),
  category JSONB,
  subject_reference VARCHAR(45),
  encounter_reference VARCHAR(45),
  period_start TIMESTAMP WITH TIME ZONE,
  period_end TIMESTAMP WITH TIME ZONE,
  care_team JSONB,
  addresses JSONB,
  activity JSONB
);""",
"""CREATE TABLE claim (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  status VARCHAR(25),
  type_coding JSONB,
  use VARCHAR(25),
  patient_reference VARCHAR(45),
  patient_display TEXT,
  billable_period_start TIMESTAMP WITH TIME ZONE,
  billable_period_end TIMESTAMP WITH TIME ZONE,
  created TIMESTAMP WITH TIME ZONE,
  provider_reference TEXT,
  provider_display TEXT,
  priority_coding JSONB,
  facility_reference TEXT,
  facility_display TEXT,
  diagnosis JSONB,
  supporting_info JSONB,
  procedure JSONB,
  prescription_reference VARCHAR(45),
  insurance JSONB,
  item JSONB,
  total_value TEXT,
  total_currency VARCHAR(4)
);""",
"""CREATE TABLE device (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  udi_carrier JSONB,
  status TEXT,
  distinct_identifier TEXT,
  manufacture_date TIMESTAMP WITH TIME ZONE,
  expiration_date TIMESTAMP WITH TIME ZONE,
  lot_number TEXT,
  serial_number TEXT,
  device_name JSONB,
  type_coding JSONB,
  type_text TEXT,
  patient_reference VARCHAR(45)
);""",
"""CREATE TABLE diagnostic_report (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  status VARCHAR(25),
  category JSONB,
  code_coding JSONB,
  subject_reference VARCHAR(45),
  encounter_reference VARCHAR(45),
  effective_date_time TIMESTAMP WITH TIME ZONE,
  issued TIMESTAMP WITH TIME ZONE,
  performer JSONB,
  result JSONB,
  presented_form JSONB
);""",
"""CREATE TABLE document_reference (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  identifier JSONB,
  status VARCHAR(25),
  type_coding JSONB,
  category JSONB,
  subject_reference VARCHAR(45),
  date TIMESTAMP WITH TIME ZONE,
  author JSONB,
  custodian_reference TEXT,
  custodian_display TEXT,
  content JSONB,
  context_encounter JSONB,
  context_period_start TIMESTAMP WITH TIME ZONE,
  context_period_end TIMESTAMP WITH TIME ZONE
);""",
"""CREATE TABLE explanation_of_benefit (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  contained JSONB,
  identifier JSONB,
  status VARCHAR(25),
  type_coding JSONB,
  use VARCHAR(25),
  patient_reference VARCHAR(45),
  billable_period_start TIMESTAMP WITH TIME ZONE,
  billable_period_end TIMESTAMP WITH TIME ZONE,
  created TIMESTAMP WITH TIME ZONE,
  insurer TEXT,
  provider_reference TEXT,
  referral_reference TEXT,
  facility_reference TEXT,
  facility_display TEXT,
  claim_reference VARCHAR(45),
  outcome TEXT,
  care_team JSONB,
  diagnosis JSONB,
  insurance JSONB,
  item JSONB,
  total JSONB,
  payment_amount_value TEXT,
  payment_amount_currency VARCHAR(4)
);""",
"""CREATE TABLE imaging_study (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  identifier JSONB,
  status VARCHAR(25),
  subject_reference VARCHAR(45),
  encounter_reference VARCHAR(45),
  started TIMESTAMP WITH TIME ZONE,
  number_of_series TEXT,
  number_of_instances TEXT,
  procedure_code JSONB,
  location_reference TEXT,
  location_display TEXT,
  series JSONB
);""",
"""CREATE TABLE immunization (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  status VARCHAR(25),
  vaccine_code_coding JSONB,
  vaccine_display TEXT,
  patient_reference VARCHAR(45),
  encounter_reference VARCHAR(45),
  occurence_date_time TIMESTAMP WITH TIME ZONE,
  primary_source TEXT,
  location_reference TEXT,
  location_display TEXT
);""",
"""CREATE TABLE medication (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  code_coding JSONB,
  code_text TEXT,
  status VARCHAR(25)
);""",
"""CREATE TABLE medication_administration (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  medication_codeable_concept_coding JSONB,
  medication_codeable_concept_text TEXT,
  subject_reference VARCHAR(45),
  context_reference VARCHAR(45),
  effective_date_time TEXT,
  reason_reference_reference VARCHAR(45),
  dosage_value TEXT,
  dosage_rate TEXT
);""",
"""CREATE TABLE medication_request (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  status VARCHAR(25),
  intent VARCHAR(25),
  medication_reference_reference VARCHAR(45),
  medication_codeable_concept_coding JSONB,
  medication_codeable_concept_text TEXT,
  subject_reference VARCHAR(45),
  encounter_reference VARCHAR(45),
  authored_on TIMESTAMP WITH TIME ZONE,
  requester_reference TEXT,
  requester_display TEXT,
  reason_reference_reference VARCHAR(45),
  dosage_instruction JSONB
);""",
"""CREATE TABLE observation (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  status VARCHAR(25),
  category JSONB,
  code_coding JSONB,
  code_text TEXT,
  subject_reference VARCHAR(45),
  encounter_reference VARCHAR(45),
  effective_date_time TEXT,
  issued TIMESTAMP WITH TIME ZONE,
  component JSONB,
  value_quantity_value TEXT,
  value_quantity_unit TEXT
);""",
"""CREATE TABLE procedure (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  status VARCHAR(25),
  code_coding JSONB,
  code_text TEXT,
  subject_reference VARCHAR(45),
  encounter_reference VARCHAR(45),
  performed_period_start TIMESTAMP WITH TIME ZONE,
  performed_period_end TIMESTAMP WITH TIME ZONE,
  location_reference TEXT,
  location_display TEXT,
  reason_reference_reference VARCHAR(45)
);""",
"""CREATE TABLE provenance (
  id VARCHAR(45) PRIMARY KEY,
  resource_type VARCHAR(50),
  resource_id VARCHAR(36),
  target JSONB,
  recorded_date TIMESTAMP WITH TIME ZONE,
  agent JSONB
);""",
]